### ISSUE TITLE
w3 login failed due to "Can't parse UCAN"

### ISSUE THREAD

**Issue by finger92** [web3-storage/w3cli#143]
the first time I ran `w3 login`, everything is ok. I registered the email and subscribed the plan. 
But when I ran again i shows

```
ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.
    at ParseError.throw (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:325:11)
    at Module.fail (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:332:47)
    at parse (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/parser.js:19:21)
    at Module.decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/codec/jwt.js:36:27)
    at Module.decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/lib.js:52:16)
    at decode (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:437:23)
    at get data [as data] (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:230:18)
    at get expiration [as expiration] (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:295:17)
    at isExpired (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/delegations.js:9:20)
    at #delegations (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/agent.js:159:18)
```

outputs of "node --version && npm --version":
```
v18.18.2
9.8.1
```

outputs of "npm list -g":
```
/usr/local/lib
├── @web3-storage/w3cli@7.0.1
├── corepack@0.19.0
├── n@9.2.0
├── npm@9.8.1
└── serverless@3.35.2
```

**Comment by sudeepdino008** [comment]
i'm getting the same error a little later in the flow:

```
➜ w3 login sudeep@covalenthq.com
⁂ Agent was authorized by did:mailto:covalenthq.com:sudeep

>> ipfs-pinner git:(w3cli_migration) ✗
➜ w3 space ls
  did:key:z6MkgSK6VEu3bvrAFtYNyjsnzG7dVXzYi3yT5TasEgeaQrCe mock_artifacts
>> ipfs-pinner git:(w3cli_migration) ✗
➜ w3 account ls
file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:325
    throw new this(message)
          ^

ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.
    at ParseError.throw (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:325:11)
    at Module.fail (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:332:47)
    at parse (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/parser.js:19:21)
    at Module.decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/codec/jwt.js:36:27)
    at Module.decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/lib.js:52:16)
    at decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:437:23)
    at get data [as data] (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:230:18)
    at get expiration [as expiration] (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:295:17)
    at isExpired (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/delegations.js:9:20)
    at #delegations (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/agent.js:159:18)

Node.js v20.5.1

```

**Comment by finger92** [comment]
I fixed this by replacing this file "https://github.com/web3-storage/w3up/blob/main/packages/access-client/src/utils/json.js" with following codes

```
// JSON.stringify and JSON.parse with URL, Map and Uint8Array type support.
/**
 * @param {string} k
 * @param {any} v
 */
export const replacer = (k, v) => {
    if (v instanceof URL) {
        return { $url: v.toString() };
    }
    else if (v instanceof Map) {
        return { $map: [...v.entries()] };
    }
    else if (v instanceof Uint8Array) {
        return { $bytes: [...v.values()] };
    }
    else if (v instanceof ArrayBuffer) {
        return { $bytes: [...new Uint8Array(v).values()] };
    }
    else if (v?.type === 'Buffer' && Array.isArray(v.data)) {
        return { $bytes: v.data };
    }
    return v;
};
/**
 * @param {string} k
 * @param {any} v
 */
export const reviver = (k, v) => {
    if (!v)
        return v;
    if (v.$url)
        return new URL(v.$url);
    if (v.$map)
        return new Map(v.$map);
    if (v.$bytes)
        return new Uint8Array(v.$bytes);
    return v;
};
/**
 * @param {any} value
 * @param {number|string} [space]
 */
export const stringify = (value, space) => JSON.stringify(value, replacer, space);
/** @param {string} value */
export const parse = (value) => JSON.parse(value, reviver);
//# sourceMappingURL=json.js.map
```

**Comment by travis** [comment]
hello - sorry about this! I've released a new version of w3cli that pins the dependency, and am about to make a change very similar to this to fix this bug - thank you for the report!
