### ISSUE TITLE
ParseError on login

### ISSUE THREAD

**Issue by sudeepdino008** [web3-storage/w3cli#149]
```bash
➜ w3 -v
w3, 7.0.3
```

when I try to login using w3, I get the following error:

```bash
➜ w3 login sudeep@covalenthq.com
ParseError: Can't parse UCAN: : Expected JWT format: 3 dot-separated base64url-encoded values.
    at ParseError.throw (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:325:11)
    at Module.fail (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/schema.js:332:47)
    at parse (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/parser.js:19:21)
    at Module.decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/codec/jwt.js:36:27)
    at Module.decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ipld/dag-ucan/src/lib.js:52:16)
    at decode (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:437:23)
    at get data [as data] (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:230:18)
    at get expiration [as expiration] (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/core/src/delegation.js:295:17)
    at isExpired (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/delegations.js:9:20)
    at #delegations (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/dist/src/agent.js:159:18)
```

**Comment by alanshaw** [comment]
Is this still happening?

If yes, please try moving your w3 store (so you have a backup) and trying again. See https://github.com/web3-storage/w3cli#where-are-my-keys-and-delegations-stored for the location.
