### ISSUE TITLE
`space register` and `authorize` need testing

### ISSUE THREAD

**Issue by travis** [web3-storage/w3cli#61]
Per https://github.com/web3-storage/w3cli/pull/60#issuecomment-1480334110 it would be good to have tests for `space register`. It would also be nice to test `authorize`.

Both of these commands interact with real services, and `space register` in particular can't execute if the test agent doesn't have any proofs. 

I've pushed a branch with the beginnings of a test for these flows:

https://github.com/web3-storage/w3cli/tree/feat/register-space-testing

but figuring out the right way to test these commands that depend on remote services is a bit of a project.

**Comment by gobengo** [comment]
```
bengo@bengo ~/protocol.ai/w3protocol/packages/access-api ⚡  w3 authorize bengo@dag.house
file:///Users/bengo/.nvm/versions/node/v18.10.0/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/principal/src/signer.js:47
    if (archive.id.startsWith('did:key:')) {
                   ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Importer.from (file:///Users/bengo/.nvm/versions/node/v18.10.0/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/principal/src/signer.js:47:20)
    at AgentData.fromExport (file:///Users/bengo/.nvm/versions/node/v18.10.0/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/access/src/agent-data.js:79:27)
    at create (file:///Users/bengo/.nvm/versions/node/v18.10.0/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/w3up-client/src/index.node.js:27:40)
    at async authorize (file:///Users/bengo/.nvm/versions/node/v18.10.0/lib/node_modules/@web3-storage/w3cli/index.js:20:18)

Node.js v18.10.0
bengo@bengo ~/protocol.ai/w3protocol/packages/access-api ⚡      
```

I'm assuming this is because I have stored state from very old verisons?
I'm willing to fully reset since this is beta. what would I do to reset my store?
