### ISSUE TITLE
Problem running w3 client

### ISSUE THREAD

**Issue by walkerlj0** [web3-storage/w3cli#71]
I installed the @web3-storage/w3cli and @web3-storage/w3up-client & cannot run any of the procesess, not sure what this error message implies:

``` 
 ~ w3 up help
file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/transport/src/http.js:30
      throw new TypeError(
            ^

TypeError: ucanto HTTP transport got undefined `fetch`. Try passing in a `fetch` implementation explicitly.
    at Module.open (file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@ucanto/transport/src/http.js:30:13)
    at file:///usr/local/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/service.js:13:17
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async file:///usr/local/lib/node_modules/@web3-storage/w3cli/shim.js:15:1
```

I get the same error when running `w3 help` as well

**Comment by travis** [comment]
@walkerlj0 I'm going to close this out since I think my solution should fix your problem, please feel free to re-open with an update if it does not!

**Comment by alexjorgef** [comment]
@walkerlj0 upgrade Node.js to 18+, I hit the same error using Node.js 16
